language: scala
scala: 2.12.6
jdk: openjdk8
dist: trusty
sudo: false

stages:
  - name: test
  - name: publish
    if: NOT type = pull_request

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.coursier/cache
    - '.hoarder-cache'

env:
  global:
    - COURSIER_PROGRESS=0
    - SBT=./sbt
    # ENCRYPTION_PASSWORD
    - secure: "gcVd+nxNvnls9pZbLUvmLDWqU9t5/34kfDFQOv8iOj3QPiS4FYPPoA/N66g/YgTOuA/yeqZoJwQw8HfJwBqc+fjBczQz37taC5wYAjnNLJYzE6iF2dbYl15g8lad2q68rvFSOcbdLMB73fDNBuZN1WDq2Go6RSxZsYZXgbXoZKmGtgod4Qs/ERPkTt5mvy5nplS/mYVWWj7fbHt9dB2PErCdxB+Gb+txlcBUNbI5MhIcfjsnlKUudgGCkTjtid9HOw/kkY+o7MVBMjIRPVJRKNK2pJRQA+SWJf1tWHk3vhrqzgrZMIrbkbaTQjxPn7TuXItWlKcd7eONe9ByPwpGml/mZvfq3BFegqCezeWaDNiKqyjxuilCUNV5C6WNOiAbWvpkkt79hhqXrA9uAxk6IeGW4e6LjNhWffZsUBd4pX1MocUKX7c+PM0oBvn9H9SJgVl7tWlnCxoGQzpbU7HT7/rmFldofbLz3fRNRmEx6XzTNV3LI3472oQxH8yanyBRUJmXwdxvm+/EL39KcOF3qwevbVCTvn7VkSEYaujOPNvt8mEpw/Yk2cf5/ISG3tA1mrzihQ9PV/NBfbxkek2B1i1Sf5ImMpL7PrsoogbCbD4NbKNh0CWvIR9/EJrRpKkZOLKUF+qaeH81tH/QMl9Z9b9zIJJ1NfKTYCUG2X34srY="
    # GITHUB_TOKEN
    - secure: "UP8462/zizkkV6svHsXJyJHhQpm8d/3H0nkRH1b6/Jf63woaZ0CwByA96JJEB/Co+P8b4ekaNqfwQVyrUqlP0r5oba4pbZPhJtXnP0TTtmv5dOd+MXGbw65di6FufXwsUFP03fFGJgeazX+QVxJfbq3Oq5idaSF1B+ee9P62Mzt9bZBvK5YlwhTyqHd9ZnZYoIAPZlWfJCNCu+YY/pe0tim0k9blTAUnxWGw6HvZYYdEg/38RJuvehr8LZ71S5b56mjI841hfdI3L56xTXvYunjyvkgFsFzk+JpKslumPRmWxJnAmPTxQsYnTYtE+u41f/apULbJZVNgUPOJo/3b8UlhjYCnD7gWOJ3PZ6B160hz7xSVwvJZDgQAd4IgDmZ+DUai4kkdPgS+9rAKT95V8j5oe/uMHgxCBRUCKx2ODhseX/6fbbn3Q7hMyjbyYT29XgSjDioeWjADpBVWWSlpVzlUf9Z6aLYpTVZqhyp1pidLzLBm6Fu9BX0n7gxWK6rP55qhQm8GrmhGyCGAY7OEyyIoTokEX7A8v8UsE++R2zhd+sPeLLibkO2ob1a+yj6t9DGahG9I34bExo5+tb3hsvA2ofesNatry4YFQCzIja+m7i4z54XL8VwQnhxjTStxurq3rj6ls/XmnSqo9D3PqO9A/VC41KNIY9NtwBt4Z00="
    # GITHUB_ACCESS_TOKEN
    - secure: "kLgfd9j3H8Ed8Odel0k52M0L1w0RMRUybHO2akPZH74g0kW15IP4qoFXgA1AJnNTVyj0R1QJYg2fxSBeDCyadkf3af76fDyVFBdpT98Ahb5qhq815Ow+howPHyuWhGmDxuI/SuReFDoztK1d9gzY5lqjg+WyCm0A65l/PNXUQaLwAV2M9bFXgYYrbXJLSBdhK2mVLLJVW6B/gTLr3eG2pt8cgscTtP6qSx31q1xZYi7Ffzt/NFq5s3q6a3ckCjqptgwoyDKw0J1rn/mDdAHGrcLRht6S9vU/ChkABpVta9xQNZuORYoDod3aAgEGBxzR/uklBo6XnqU330SEDSBtH9Rt0M6Fr83CARPe920pDXOKZ1oY1w/tZsBH397PAWBX6YpMKq9UrkG9Yv5c6mSdpMhq9gkUky9WzZvS12yXbPomSugh8caxuaQTb5WR0KdBlFB4MOVduEac7DLVDzxGCcSRbB2ORE4oNjm7oDSQmmYWHuvlCqp0ZLpVxaflNFusWBRbvc6Mmkstf0m1yvV/TvV3FMx7Z3SujrA+xXDKRoVrsCP1dz/c1jN4gQ+YQ0L2LmT8OFU7RcL3GwgS4Akla4x4dbk7BlqrXtiL1I4YcTpMRuqDsnr7IX1fgXozagYEhRUMFW+Wl6K3IKYM3uwJL2Z8Ks1oOk1ln9FPavTIGCk="
    # DISCORD_WEBHOOK_TOKENS
    - secure: "iSUPH0sZb9jT+qeTYPOMNJlIxmyGx8gB4qo4SjcFnaSp4YYJJ2DLwMxXaesyBoU9JyF+jSTKOIZJttFAouglbW4YgLl22x+Wihcs86AyJfYz9I9GwL0pF3iwBbc3pyt9+ghK6EVt2MDlTdFGihBVTGw9Pye+uHsUOPiin/v2GBxLz6HZtyYVWx6eLRSB3nNEgaWpQXkAy1kKAD06nl9jOPBlT70ahgX6kmtvoa+BrMJBhvRoGH7pOOIVox8cl0UMta4VCkDb9BmxK6npFoBfy0/svwoTCF2FCBi71E8xhUXr5sAxZ3AphIOaiDDpZvW7po+C1O7+jX+uM26jMZ+ekh9SSHtdFtWW/dl/lM4Jprd8yjrssed4hw34yXT/YMtWjoaZ75ly7/BfT1mQRUZkWs8fBnoyDdYH/ZW20jo6ahpQc+TFyzy0tRSWRIMLTXWzNl2DtCcjjwW2NM8iT0FQuOVhu2YCPF1ni5xgcb7RejPQgvTD4cpSv0vTO3Fu+mPx2nrHs0lG7SGSMEoXD+mlPqbSb/uacBEyKjP0zVbt2EZPjOzw6TPI4tbAoltOlHH+bzsJfhbkpnxNaczJL6QjLGTJZXkCRB0/1ka/GSYnBDiS9Y3EG9Z5CuudBT7zEkAVNlAnTTXgbrW0LIE0HWy5BQNOxxBRuQeA0mow8IVrnSI="

install:
  - mkdir scripts
  - $SBT transferCommonResources
  - scripts/commonSetup

jobs:
  include:
    - stage: test
      script:
        - set -e
        # Just protecting against automated scrapers
        - base64 -d testCredentials.json.b64 > testCredentials.json
        - $SBT ++$TRAVIS_SCALA_VERSION test

    - stage: publish
      env:
      script:
        - set -e
        - $SBT transferPublishAndTagResources
        - TRAVIS_JOB_NUMBER=1 scripts/publishAndTag 'slamdata/quasar-datasource-s3'
        - bumpInDownstream() { echo $1 > slamdata-s3-version; }
        - export -f bumpInDownstream
        - scripts/bumpDependentProject slamdata slamx bumpInDownstream
      git:
        depth: false

after_success:
  - scripts/checkAndAutoMerge
  - scripts/discordTravisPost success https://discordapp.com/api/webhooks/$DISCORD_WEBHOOK_TOKENS

after_failure:
  - scripts/discordTravisPost failure https://discordapp.com/api/webhooks/$DISCORD_WEBHOOK_TOKENS

branches:
  only:
    - master
    - /^backport.*$/

before_cache:
  - find "$HOME/.sbt/" -name '*.lock' -print0 | xargs -0 rm
  - find "$HOME/.ivy2/" -name 'ivydata-*.properties' -print0 | xargs -0 rm
