language: scala
scala: 2.12.4
jdk: oraclejdk8
dist: trusty
sudo: false
script:
  - sbt test lwc/assembly
branches:
  except:
  - /^v\d+\.\d+\.\d+$/ # don't redundantly build tags
cache:
  directories:
  - $HOME/.coursier/cache
  - $HOME/.ivy2/cache
  - $HOME/.sbt
before_cache:
  - find "$HOME/.sbt/" -name '*.lock' -print0 | xargs -0 rm
  - find "$HOME/.ivy2/" -name 'ivydata-*.properties' -print0 | xargs -0 rm
deploy:
  provider: releases
  api_key:
    secure: "W7dalSaVSxIveCTs6H+gZjETdrp26MJr5/q5uncg2R3uEJ3WteejYahLih9DoYAekyegJznxF3pyc9Jha+j9n77BaFVzhYJEOaz8C1tBaw8oxfts3yohfAluxZ/oZ7sweCiIoFUv0Txb3aCPanwOj9u1mL/7ogFfyuN3O74HxPmeKTczjLVZklHnnqp/1gtdkrshKVuwpprwlq8gdZbZ9pOr9Lrm0AjcKjMXk0gze8pfBC5gDQZTdHJobxBsIQq+uwpQegEwc4hwzAtWKjzCxRuuQM63IoANo+f1PEAlbEPNyku02cjqNikVVxKSSEiNgn2MdS9/8/PRnCOi4ubzYqRIeiipynlcjcyfj/DeAL277+9IZwpl8e1TW0emrwkZXrK+P++i9LAWVByOa2rkJTj0iVfJanR1NKbehUeUo73YKE+eRmwpuP2KtvnKxgYTOuNYwbmYHVlcVc3zsJTCQqbe6cwhOmDOAve4knp7ceELRdBQ5nPaq93VIOWQMjd9PwuH/VJaVczS1aTJZHF//un8BYqlFbGHjGR5hB1eylSLlZDY2otzM6SdpsnNaC4qv+jVRD1GrfNiOoUVCBnbSQrr5lvr0i/BkRViQrluf6cWI0OnekY2os1IOewJcAjqwWCT6qKxj2LSVrDPxlgXobfaaZC5dZioKlii84GW7lg="
  file_glob: true
  file:
    - .targets/lwc/scala-2.12/lwc.jar
  skip_cleanup: true
  script:
    - ./scripts/version
  on:
    tags: false
    #all_branches: true
    # Omit tagged builds and publish on master and backport/*
    #condition: $TRAVIS_TAG = '' && ($TRAVIS_BRANCH == "master" || $TRAVIS_BRANCH == backport/*)


before_deploy:
  - scripts/lwcPublishAndTag
